apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: login-api-ingress
  namespace: apps-anchieta-mobile-ios
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: anchieta-mobile-ios-login.local
      http:
        paths:
          - path: /

            pathType: Prefix
            backend:
              service:
                name: login-api
                port:
                  number: 8085
