apiVersion: v1
kind: Namespace
metadata:
  name: apps-anchieta-mobile-ios
---
apiVersion: v1
kind: Service
metadata:
  name: login-api
  namespace: apps-anchieta-mobile-ios
spec:
  type: NodePort
  ports:
    - port: 8085
      targetPort: 8085
      nodePort: 30085
  selector:
    app: login-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-api
  namespace: apps-anchieta-mobile-ios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-api
  template:
    metadata:
      labels:
        app: login-api
    spec:
      imagePullSecrets:
        - name: nexus-pull-secret
      containers:
        - name: login-api
          image: 192.168.1.33:5000/anchieta-mobile-ios-repository/api-login:latest

          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: login-api-secrets
                  key: db-url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: login-api-secrets
                  key: db-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: login-api-secrets
                  key: db-pass
            - name: KEYCLOAK_URL
              value: "http://keycloak.infra.svc.cluster.local:8080"
            - name: KEYCLOAK_REALM
              value: "anchieta-mobile-ios-realm"
            - name: KEYCLOAK_CLIENT_ID

              value: "registration-api-client"
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: login-api-secrets
                  key: keycloak-client-secret
          ports:
            - containerPort: 8085
          resources:
            limits:
              memory: "512Mi"
            requests:
              memory: "256Mi"
