name: Build and Push API

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Nexus Docker Registry
        run: |
          echo "${{ secrets.NEXUS_PASSWORD }}" | docker login ${{ vars.NEXUS_URL }} -u ${{ vars.NEXUS_USER }} --password-stdin

      - name: Build and Tag Docker Image (Login API)
        run: |
          cd api-projects/anchieta-pfinal-login
          # Extrai a versão usando um container temporário do Maven
          VERSION=$(docker run --rm -v "$(pwd)":/app -w /app maven:3.9.6-eclipse-temurin-17 mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          docker build -t ${{ vars.NEXUS_URL }}/anchieta-mobile-ios-repository/api-login:latest .
          docker tag ${{ vars.NEXUS_URL }}/anchieta-mobile-ios-repository/api-login:latest ${{ vars.NEXUS_URL }}/anchieta-mobile-ios-repository/api-login:$VERSION

      - name: Build and Tag Docker Image (AI API)
        run: |
          cd api-projects/anchieta-pfinal-ai
          # Extrai a versão usando um container temporário do Maven
          VERSION=$(docker run --rm -v "$(pwd)":/app -w /app maven:3.9.6-eclipse-temurin-17 mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          docker build -t ${{ vars.NEXUS_URL }}/anchieta-mobile-ios-repository/api-ai:latest .
          docker tag ${{ vars.NEXUS_URL }}/anchieta-mobile-ios-repository/api-ai:latest ${{ vars.NEXUS_URL }}/anchieta-mobile-ios-repository/api-ai:$VERSION

      - name: Push Images to Nexus
        run: |
          # Pegando as versões novamente usando Docker para o push
          VERSION_LOGIN=$(docker run --rm -v "$(pwd)/api-projects/anchieta-pfinal-login":/app -w /app maven:3.9.6-eclipse-temurin-17 mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          VERSION_AI=$(docker run --rm -v "$(pwd)/api-projects/anchieta-pfinal-ai":/app -w /app maven:3.9.6-eclipse-temurin-17 mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          
          docker push ${{ vars.NEXUS_URL }}/anchieta-mobile-ios-repository/api-login:latest
          docker push ${{ vars.NEXUS_URL }}/anchieta-mobile-ios-repository/api-login:$VERSION_LOGIN
          docker push ${{ vars.NEXUS_URL }}/anchieta-mobile-ios-repository/api-ai:latest
          docker push ${{ vars.NEXUS_URL }}/anchieta-mobile-ios-repository/api-ai:$VERSION_AI