name: Build and Push API

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Nexus Docker Registry
        run: |
          echo "${{ secrets.NEXUS_PASSWORD }}" | docker login ${{ vars.NEXUS_URL }} -u ${{ vars.NEXUS_USER }} --password-stdin

      - name: Build and Tag Docker Image
        run: |
          cd api-projects/anchieta-pfinal-login
          # Usamos o novo nome do repositório: anchieta-mobile-ios-repository
          docker build -t ${{ vars.NEXUS_URL }}/anchieta-mobile-ios-repository/api-login:latest .
          docker tag ${{ vars.NEXUS_URL }}/anchieta-mobile-ios-repository/api-login:latest ${{ vars.NEXUS_URL }}/anchieta-mobile-ios-repository/api-login:${{ github.sha }}

      - name: Push Image to Nexus
        run: |
          docker push ${{ vars.NEXUS_URL }}/anchieta-mobile-ios-repository/api-login:latest
          docker push ${{ vars.NEXUS_URL }}/anchieta-mobile-ios-repository/api-login:${{ github.sha }}
